### ISSUE TITLE
Obtain Images from Search URL

### ISSUE THREAD

**Issue by BFMarks** [pts/flickrurlget#1]
Hey cool code, 

How can I obtain images from the search URL like: 
`https://www.flickr.com/search/?text=search_item`

**Comment by pts** [comment]
`flickrurlget` currently doesn't support downloading search results.

This feature can probably be added by extending the `yield_tagged_photos` function. Instead of

```
'tags': tag,
```

one could write:

```
'text': 'search_item',
```

Based on this doc: https://www.flickr.com/services/api/flickr.photos.search.html

Please note that since I'm busy with other work, I'm unlikely to add this feature myself. If anyone needs it, please send a pull request.
